package tn.esprit.EldSync.model;

public enum AlertType {
    OXYGEN_SATURATION_LOW,
    TEMPERATURE_HIGH,
    HEART_RATE_OUT_OF_RANGE,
    RESPIRATORY_RATE_OUT_OF_RANGE,
    CHOLESTEROL_HIGH,
    BLOOD_GLUCOSE_HIGH,
    WEIGHT_OUT_OF_RANGE
}
